# Generated by Django 3.1.6 on 2021-02-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0005_auto_20210215_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='status',
        ),
    ]
