# Generated by Django 3.1.6 on 2021-02-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0007_auto_20210216_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='arrivaltime',
            field=models.TimeField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='bookdate',
            field=models.DateField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='mealplan',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='purpose',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('casual', 'Casual'), ('celebration', 'Celebration')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='typeoftable',
            field=models.CharField(choices=[('table of 2 Guest', 'Table OF 2 Guest'), ('table of 3 Guest', 'Table OF 3 Guest'), ('table of 4 Guest', 'Table OF 4 Guest'), ('table of 5 Guest', 'Table OF 5 Guest'), ('table of 6 guest', 'Table OF 6 Guest')], max_length=50, null=True),
        ),
    ]
