# Generated by Django 3.1.6 on 2021-02-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0008_auto_20210216_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='typeoftable',
            field=models.CharField(choices=[('table of 2 Guest', 'Table of 2 Guest'), ('table of 3 Guest', 'Table of 3 Guest'), ('table of 4 Guest', 'Table of 4 Guest'), ('table of 5 Guest', 'Table of 5 Guest'), ('table of 6 guest', 'Table of 6 Guest')], max_length=50, null=True),
        ),
    ]
