# Generated by Django 3.1.6 on 2021-02-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0009_auto_20210216_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='bookdate',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
