# Generated by Django 3.1.6 on 2021-02-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0010_auto_20210216_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='bookdate',
            field=models.DateField(max_length=40, null=True),
        ),
    ]
