# Generated by Django 3.1.6 on 2021-02-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0011_auto_20210216_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='mealplan',
            field=models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=40, null=True),
        ),
    ]
