# Generated by Django 3.1.6 on 2021-02-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='title',
        ),
    ]
