# Generated by Django 3.1.6 on 2021-02-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0014_auto_20210216_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='mealplan',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='purpose',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('Casual', 'Casual'), ('Celebration', 'Celebration')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='typeoftable',
            field=models.CharField(choices=[('Table of 2 Guest', 'Table of 2 Guest'), ('Table of 3 Guest', 'Table of 3 Guest'), ('Table of 4 Guest', 'Table of 4 Guest'), ('Table of 5 Guest', 'Table of 5 Guest'), ('Table of 6 guest', 'Table of 6 Guest')], max_length=50, null=True),
        ),
    ]
