# Generated by Django 3.1.6 on 2021-02-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_reservations_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
