# Generated by Django 3.1.6 on 2021-02-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_reservations_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservations',
        ),
    ]
